# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96debbe05f5bc925d7a3b2b975cb88a3b940fc678c8e3f2361c89888e1326880a237a63fb4f6d0dbfc5db71fd0606cba41a741d949fd7e160fa000d749832c99

test:
  secret_key_base: d4224a13c65eb667d826226e920a79aa13aad687c773d8f2a5cdd2ca9840366b7d51900f53fa171fe991b2fc744cd085e5a52f5a411b176e64872c442a00bd95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
